services:
  - type: web
    name: online-quiz
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --worker-class geventwebsocket.gunicorn.workers.GeventWebSocketWorker -w 1 run:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        sync: false
      - key: MASTER_CODE
        sync: false
      - key: QR_PUBLIC_URL
        value: "https://online-quiz-9gez.onrender.com/student"
